// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParsiDNS.DataLayer.Context;

#nullable disable

namespace ParsiDNS.DataLayer.Migrations
{
    [DbContext(typeof(ParsiDnsContext))]
    partial class ParsiDnsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParsiDNS.DataLayer.Entities.DNS", b =>
                {
                    b.Property<int>("DnsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DnsId"));

                    b.Property<string>("Dns1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Dns2")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DnsId");

                    b.ToTable("DNS");
                });

            modelBuilder.Entity("ParsiDNS.DataLayer.Entities.DnsSoftwares", b =>
                {
                    b.Property<int>("DS_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DS_Id"));

                    b.Property<int>("DnsId")
                        .HasColumnType("int");

                    b.Property<int>("LastMonthLikeCount")
                        .HasColumnType("int");

                    b.Property<int>("LastWeekLikeCount")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<int>("TotalLikeCount")
                        .HasColumnType("int");

                    b.HasKey("DS_Id");

                    b.HasIndex("DnsId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("DnsSoftware");
                });

            modelBuilder.Entity("ParsiDNS.DataLayer.Entities.Software", b =>
                {
                    b.Property<int>("SoftwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SoftwareId");

                    b.ToTable("Software");
                });

            modelBuilder.Entity("ParsiDNS.DataLayer.Entities.DnsSoftwares", b =>
                {
                    b.HasOne("ParsiDNS.DataLayer.Entities.DNS", "DNS")
                        .WithMany("DnsSoftwares")
                        .HasForeignKey("DnsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParsiDNS.DataLayer.Entities.Software", "Software")
                        .WithMany("DnsSoftwares")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DNS");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("ParsiDNS.DataLayer.Entities.DNS", b =>
                {
                    b.Navigation("DnsSoftwares");
                });

            modelBuilder.Entity("ParsiDNS.DataLayer.Entities.Software", b =>
                {
                    b.Navigation("DnsSoftwares");
                });
#pragma warning restore 612, 618
        }
    }
}
